### ISSUE TITLE
Returns nothing...

### ISSUE THREAD

**Issue by dc500** [YoongiKim/AutoCrawler#11]
1 keywords found: ['BTS']
Detected OS : Mac
Detected OS : Mac
Task ended. Pool join.
Data imbalance checking...
Data imbalance not detected.

(Yes, I tested with BTS).

**Comment by r3a2t10** [comment]
Hello~ I met the same problem on Linux
You can try download the newest chormedriver
https://chromedriver.chromium.org/
and replace in the folder "chromedriver"
and change the code in  collect_links.py with new driver file path

        if platform.system() == 'Windows':
            print('Detected OS : Windows')
            executable = './chromedriver/chromedriver'
        elif platform.system() == 'Linux':
            print('Detected OS : Linux')
            executable = './chromedriver/chromedriver'
        elif platform.system() == 'Darwin':
            print('Detected OS : Mac')
            executable = './chromedriver/chromedriver'

I fixed it by this way
Hope it work for you too :)

**Comment by YoongiKim** [comment]
Hello, thanks for contributions!

I've updated chrome-driver version.

And added **version checking** features
![image](https://user-images.githubusercontent.com/38288705/62880902-7396f700-bd69-11e9-80f7-bcde11171b03.png)

Thank you :)

**Comment by dc500** [comment]
> Hello, thanks for contributions!
> 
> I've updated chrome-driver version.
> 
> And added **version checking** features
> ![image](https://user-images.githubusercontent.com/38288705/62880902-7396f700-bd69-11e9-80f7-bcde11171b03.png)
> 
> Thank you :)

감사합니다-!!  대박이다!! :)
