### ISSUE TITLE
google crawl issue regarding ChromeDriver

### ISSUE THREAD

**Issue by Ella77** [YoongiKim/AutoCrawler#18]
Thank you for the great repository for auto crawling and really enjoyed using my linux server to crawl images.

But now, google crawling(not Naver) wouldn't work any more, just done with non e image. 

I did some test on my local Mac environment on conditions below(with updated ChromeDriver version), but the result was successful. 
```
Current web-browser version:    79.0.3945.130
Current chrome-driver version:  78.0.3904.70

Current web-browser version:	79.0.3945.130
Current chrome-driver version:	79.0.3945.36

```
For linux, there is some error 
Error occurred while initializing chromedriver - Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

so I just fixed with some solutions for running the code. 
```
chrome_options = Options()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
 webdriver.Chrome('/path/to/your_chrome_driver_dir/chromedriver',chrome_options=chrome_options)
        self.browser = webdriver.Chrome(executable,options=chrome_options)

```
I guess this code can be the key for this issue, because Mac can't crawl google contents either in this environment. 
 there are some version issue regarding ChromeDriver or maybe Google and headless option that can't crawl the content.

Wait for help and I'd be happy to contribute if I can fix it.

**Comment by YoongiKim** [comment]
I've updated chromedriver to v80.
So it would fixed your issue... I couldn't reproduce your error in my Ubuntu 18.04 machine at v80.
Please update your chrome to newest version. https://www.google.com/intl/en/chrome/

```
_________________________________
Current web-browser version:	80.0.3987.87
Current chrome-driver version:	80.0.3987.16
_________________________________
```

As google recently updating image-site rapidly, I've fixed much of the code.

1. Fixed XPATH codes.
2. Google's new image site will show 20 top images as compressed base64 image.
So I've added waiting function not to download compressed image in <b>full</b> mode.
3. Highlight at selected element.
4. Base64 image downloadable.
5. Keep order of downloaded images same as google site.
6. Old code is at ```old-google``` branch.

Please check is program working fine.
Thank you.

**Comment by Ella77** [comment]
> I've updated chromedriver to v80.
> So it would fixed your issue... I couldn't reproduce your error in my Ubuntu 18.04 machine at v80.
> Please update your chrome to newest version. https://www.google.com/intl/en/chrome/
> 
> ```
> _________________________________
> Current web-browser version:	80.0.3987.87
> Current chrome-driver version:	80.0.3987.16
> _________________________________
> ```
> 
> As google recently updating image-site rapidly, I've fixed much of the code.
> 
> 1. Fixed XPATH codes.
> 2. Google's new image site will show 20 top images as compressed base64 image.
>    So I've added waiting function not to download compressed image in full mode.
> 3. Highlight at selected element.
> 4. Base64 image downloadable.
> 5. Keep order of downloaded images same as google site.
> 6. Old code is at `old-google` branch.
> 
> Please check is program working fine.
> Thank you.

@YoongiKim  Thanks a lot!
