### ISSUE TITLE
The resolution

### ISSUE THREAD

**Issue by Tengfei000** [YoongiKim/AutoCrawler#21]
I set the 'full_resolution=True'. The resolutions of images are still very small. How to obtain the high quality images.

**Comment by men9xuan** [comment]
I modified line 54 of main.py

`  def __init__(self, skip_already_exist=True, n_threads=4, do_google=True, do_naver=True, download_path='download',
                 full_resolution=False, face=False, no_gui=False): `

and  line 326 
but now the problem becomes to SSL error for most https content

**Comment by YoongiKim** [comment]
You may try
```
python main.py --full true
```

I tested on my pc and working fine.
Can you give me more information?

**Comment by Yaoxingtian** [comment]
> 

It's cannot work for me, i met this problem too. it downloads small pictures even though i set --full true

**Comment by YoongiKim** [comment]
I have fixed the issue. Please check it out.
