### ISSUE TITLE
How to download limited images?

### ISSUE THREAD

**Issue by PosoSAgapo** [YoongiKim/AutoCrawler#25]
This project is awesome. But how could I download only limted number of images, since only images that on the first page is most important.

**Comment by YoongiKim** [comment]
I added feature to limit maximum count of images.

Try
```
python main.py --limit 100
```

**Comment by shin8256** [comment]
대단하십니다 그런데 메인파이썬의 어디 숫자를 고쳐야 할까요 ;;

**Comment by shin8256** [comment]
대단하십니다 그런데 메인 파이썬의 어디 숫자를 고쳐야할까요 ;;

**Comment by shin8256** [comment]
대단하시네요  그런데 어디를 고쳐야 숫자 제한인건지요;;;

**Comment by shin8256** [comment]
대단하시네요 존경스럽습니다. 그런데 어디를 고쳐야 숫자 제한인건지요;;;

**Comment by YoongiKim** [comment]
실행하실때 limit 옵션을 넣으실 수 있습니다.
```python3 main.py``` 또는 ```python3 main.py --limit 0``` 로 실행하시면 기본값으로 무한대이고
```python3 main.py --limit number``` 예를들어 ```python3 main.py --limit 500``` 이면 500장 제한입니다.

**Comment by shin8256** [comment]
빠른 답변 감사합니다.생초보라 너무 어려운데 정말 멋진분을 알게 됬네요 ㅎ
님 홈페이지 자주 보겠습니다 감사합니다
