### ISSUE TITLE
Full size image?

### ISSUE THREAD

**Issue by LucyLu-LX** [YoongiKim/AutoCrawler#3]
Hi, the code runs perfectly!
I noticed that the downloaded images are thumbnails.
Is there any way I can download the full images?
Thanks.

**Comment by litcoderr** [comment]
We will work on that functionality. Thanks for your suggestion 😀

**Comment by YoongiKim** [comment]
Now you can use full resolution mode!
Just specify --full true
But this method is far slower because we have to check all of the src links.
Thanks.
