### ISSUE TITLE
 ContextResult::kTransientFailure: Failed to send GpuChannelMsg_CreateCommandBuffer.

### ISSUE THREAD

**Issue by NetLSS** [YoongiKim/AutoCrawler#31]
`[1216/201931.548:ERROR:command_buffer_proxy_impl.cc(122)] ContextResult::kTransientFailure: Failed to send GpuChannelMsg_CreateCommandBuffer.`

I've always been using it well, but suddenly I get this error message. What should I do?

**Comment by NetLSS** [comment]
and this too
`This version of ChromeDriver only supports Chrome version 85
`
even if it was ver85

**Comment by YoongiKim** [comment]
Can you try installing newest chrome version (87.0.4280.88)?
And download newest chrome driver version (https://chromedriver.storage.googleapis.com/index.html?path=87.0.4280.88)

**Comment by YoongiKim** [comment]
I have fixed this issue. Please try again.

**Comment by NetLSS** [comment]
it works. but not save image

**Comment by NetLSS** [comment]
I found the cause. The GPU driver update will solve the problem. Thank you for your support.
