### ISSUE TITLE
This version of ChromeDriver only supports Chrome version 87

### ISSUE THREAD

**Issue by nguyennhunai** [YoongiKim/AutoCrawler#33]
Log Error: "Error occurred while initializing chromedriver - Message: session not created: This version of ChromeDriver only supports Chrome version 87
Current browser version is 89.0.4389.90 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome"

Resolve:
1. Install web driver from pip:
pip install webdriver-manager
2. Replace init webdriver in file collect_links.py
self.browser = webdriver.Chrome(ChromeDriverManager().install(), chrome_options=chrome_options)

**Comment by YoongiKim** [comment]
Oh, does webdriver-manager automatically install new chromedriver?

**Comment by rajatIIT** [comment]
still not working :/ 
says : Error occurred while initializing chromedriver - name 'ChromeDriverManager' is not defined

**Comment by yiyuezhuo** [comment]
You can download corresponding drivers from http://chromedriver.chromium.org/downloads manually and replace the old one with the new one.

**Comment by vandersonpaim** [comment]
npm install chromedriver --chromedriver_version=xxx

https://www.npmjs.com/package/chromedriver

**Comment by vt-mishra** [comment]
A total of 1 test files matched the specified pattern.
Invalid deployment item: the specified path '|DataDirectory|\testdata.xml' or output directory '' contains illegal characters.
##[error]Invalid settings 'TestRunParameters'. Unexpected XmlElement: 'add'.
  Failed WEBTestLeadToOpportunityBPF [24 s]
  Error Message:
   Test method Microsoft.Dynamics365.UIAutomation.Sample.Web.BusinessProcessFlow.WEBTestLeadToOpportunityBPF threw exception: 
System.InvalidOperationException: session not created: This version of ChromeDriver only supports Chrome version 108
Current browser version is 121.0.6167.140 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe (SessionNotCreated)
using .Net Framework
