### ISSUE TITLE
Download failed - check_hostname requires server_host name

### ISSUE THREAD

**Issue by JingzhiYAN** [YoongiKim/AutoCrawler#35]
Download failed -  check_hostname requires server_hostname
Downloading cat from google: 1 / 700
Download failed -  check_hostname requires server_hostname
Downloading cat from google: 1 / 700
Download failed -  check_hostname requires server_hostname
Downloading cat from google: 1 / 700
Download failed -  check_hostname requires server_hostname
Downloading cat from google: 1 / 700
Download failed -  check_hostname requires server_hostname
Downloading cat from google: 1 / 700
Download failed -  check_hostname requires server_hostname
Downloading cat from google: 1 / 700
Download failed -  check_hostname requires server_hostname
Downloading cat from google: 1 / 700
Download failed -  check_hostname requires server_hostname
Downloading cat from google: 1 / 700
Download failed -  check_hostname requires server_hostname
Downloading cat from google: 1 / 700
Download failed -  check_hostname requires server_hostname
Task ended. Pool join.
Data imbalance checking...
dir: download/cat, file_count: 0
Data imbalance not detected.
End Program

After I close the VPN I'm using, the naver works fine, but google is dead in my country..
Although I can see selenium open google and doing the whole thing, I cannot download anything.

Can you help me?

**Comment by bbbeach** [comment]
Hello
      Are you solve this problem?
