### ISSUE TITLE
python main.py --full true

### ISSUE THREAD

**Issue by zcswdt** [YoongiKim/AutoCrawler#39]
Excuse me, I saw that your code has been updated, and I re-use python main.py --full true now, but it produces thumbnails instead of full images.
![naver_0003](https://user-images.githubusercontent.com/43515926/137501615-16b354b1-a9f5-45a2-b95e-65f7a1bbe312.jpg)
![naver_0004](https://user-images.githubusercontent.com/43515926/137501688-7d2bbc73-80a2-4cba-a1ee-9d8fa95e6dd0.jpg)
![naver_0006](https://user-images.githubusercontent.com/43515926/137501708-1313b85f-6007-466f-bae9-271b48638563.jpg)

**Comment by YoongiKim** [comment]
Oh, I will check it tomorrow. thanks.

**Comment by zcswdt** [comment]
> tomorrow
Thank you

**Comment by qkum** [comment]
for me it downloads both thumbnails and the full images with --full true.

this was written: 21 may 2022.

**Comment by YoongiKim** [comment]
I found the issue, and it downloaded both thumbnail and original image.
I have fixed the issue.
