### ISSUE TITLE
Google download can not work

### ISSUE THREAD

**Issue by FlyEgle** [YoongiKim/AutoCrawler#4]
I set the --google true and naver fasle , it can not download image.But I set naver True it can download. What this mean?

**Comment by YoongiKim** [comment]
I think I made a mistake on if~elif statement.

auto_crawler.py
...
if site_code == Sites.GOOGLE:
                links = collect.google(keyword)

[-]elif site_code == Sites.NAVER:
[+]if site_code == Sites.NAVER:
                links = collect.naver(keyword)

**Comment by FlyEgle** [comment]
i try

**Comment by FlyEgle** [comment]
I have try，but it also not work.
python3 auto_crawler.py --threads 4 --google true --naver False
Options - skip:True, threads:4, google:True, naver:False
1 keywords found: ['Crocodilia']
Detected OS : Darwin
Collecting links... Crocodilia from google
Scrolling down
Exception google:Crocodilia - Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@value="결과 더보기"]"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.44.609545 (c2f88692e98ce7233d2df7c724465ecacfe74df5),platform=Mac OS X 10.14.0 x86_64)

pool join
Data imbalance checking...
Data imbalance not detected.
End Program

**Comment by YoongiKim** [comment]
I think language is problem because I made crawler in Korean.

change this to your own language...
{"method":"xpath","selector":"//input[@value="결과 더보기"]"}

to something like this

{"method":"xpath","selector":"//input[@value="Show more results"]"}

**Comment by YoongiKim** [comment]
You can change in collect_links.py

try:
            btn_more = self.browser.find_element(By.XPATH, '//input[@value="결과 더보기"]') <---------
            btn_more.click()

I will fix this later because i'm outside now.

**Comment by FlyEgle** [comment]
ok, thx

**Comment by YoongiKim** [comment]
I fixed it.
