### ISSUE TITLE
Results in limited number of images... why?

### ISSUE THREAD

**Issue by songbird39** [YoongiKim/AutoCrawler#43]
Hello, 

I am crawling using keywords in various languages, and your repo has been a tremendous help!
The code worked perfectly until last week and I could get 100s ~ 1000s of images for each search entry.
But now it fails to crawl more than 40 images, even for most popular languages.
Do you have any idea why this happens & how to fix this issue?

Thank you!

![image](https://user-images.githubusercontent.com/50364722/167580619-37e602a0-81bd-41ec-a7f3-3f24e36ab864.png)

**Comment by qkum** [comment]
same here, it does not go over 50.

with most searches far below 50 images.
+ it downloads both the thumbnail and the full resolution image with --full true.
so, in reality it downloads below 25 images at maximum.

google must have tweaked their algos...so now the code needs a tweak.

**Comment by qkum** [comment]
ok, i found one solution.

it seems that if i can figure out how to remove the `=a340` at the end of some of the download links it spits out in terminal, that it will direct to the image in full size instead of 340 resolution.

**Comment by qkum** [comment]
i recommend giving this project a try instead:
`https://github.com/alirezamika/autoscraper`

it works for simple scraping out of the gate.
perfect for beginners to this field it seems.
takes 10 min to install and 10 min to figure out how to use it with great results.

edit: 
it at least gives a list with the correct images and in full resolution if you want so, but it does not download the images.
so, this project can be used for downloading the images if you want. 
i may ending up only using the download function of this project and use the other project for getting the correct image urls to download.

or just make a `for loop` that downloads all the images with `wget ImageUrl.com` 😆  (wget only works on linux btw)
with a random delay between every image ofc.
