### ISSUE TITLE
Exception google:cat - 'WebDriver' object has no attribute 'find_element_by_tag_name'

### ISSUE THREAD

**Issue by adsf0427** [YoongiKim/AutoCrawler#44]
when I run the program, this problem oocured:
Exception google:cat - 'WebDriver' object has no attribute 'find_element_by_tag_name'

**Comment by justcodew** [comment]
replace  find_element_by_tag_name with self.browser.find_element(By.TAG_NAME,"")
        # elem = self.browser.find_element_by_tag_name("body")
        elem = self.browser.find_element(By.TAG_NAME,"body")

**Comment by YoongiKim** [comment]
Thank you for commenting! Error fixed now.
