### ISSUE TITLE
Google image crawling does not work.

### ISSUE THREAD

**Issue by dedtechsolutions** [YoongiKim/AutoCrawler#50]
[Exception occurred while collecting links from google_full] Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="k7O2sd"]"}
  (Session info: headless chrome=113.0.5672.127)
Stacktrace:
Backtrace:
        GetHandleVerifier [0x006A8893+48451]
        (No symbol) [0x0063B8A1]
        (No symbol) [0x00545058]
        (No symbol) [0x00570467]
        (No symbol) [0x0057069B]
        (No symbol) [0x00569631]
        (No symbol) [0x0058A304]
        (No symbol) [0x00569586]
        (No symbol) [0x0058A614]
        (No symbol) [0x0059C482]
        (No symbol) [0x0058A0B6]
        (No symbol) [0x00567E08]
        (No symbol) [0x00568F2D]
        GetHandleVerifier [0x00908E3A+2540266]
        GetHandleVerifier [0x00948959+2801161]
        GetHandleVerifier [0x0094295C+2776588]
        GetHandleVerifier [0x00732280+612144]
        (No symbol) [0x00644F6C]
        (No symbol) [0x006411D8]
        (No symbol) [0x006412BB]
        (No symbol) [0x00634857]
        BaseThreadInitThunk [0x75EE7D59+25]
        RtlInitializeExceptionChain [0x770AB74B+107]
        RtlClearBits [0x770AB6CF+191]

**Comment by YoongiKim** [comment]
The error occurred because the Google site was modified.
I fixed the issue, please check it out.

**Comment by sebastianelsner** [comment]
I think this is again the case

**Comment by cloudlakecho** [comment]
@dedtechsolutions Do you solve the error? It looks like you're using old "collect_links.py" code. I don't see "k7O2sd" anymore. There was [a commit](https://github.com/YoongiKim/AutoCrawler/commit/254a2e3d7f63c74bea4ca58b4055c2c498697e1d), which removed "xpath" of "k702sd" value of the "loading_bar".

**Comment by YoongiKim** [comment]
I have fixed the issue. Please checkout.
