### ISSUE TITLE
google-chrome: not found

### ISSUE THREAD

**Issue by chloesun** [YoongiKim/AutoCrawler#57]
I use WSL2 on Windows machine to test this repo, and here are some behaviors I experienced. Hope to get some guidance:
Install Chrome driver
![chrome](https://github.com/YoongiKim/AutoCrawler/assets/13730281/53888482-5cc6-435a-bfc2-263f92162430)
Run `main.py` from another terminal
`google-chrome:not found`

![LINUX](https://github.com/YoongiKim/AutoCrawler/assets/13730281/afab8c43-008d-4300-a311-fe86a99c73e0)
How to resolve this? Thank you!

**Comment by YoongiKim** [comment]
You cannot run chrome on WSL2 because it is not installed.
