### ISSUE TITLE
Selenium version issue and ChromeDriverManager

### ISSUE THREAD

**Issue by IndigoJSilver** [YoongiKim/AutoCrawler#58]
Selenium version is currently updated. Therefore, you must specify the version of selenium==4.9.0 for requirements.txt.
If you don't specify

self.browser = webdriver.Chrome(ChromeDriverManager().install(), chrome_options=chrome_options)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: WebDriver.init() got an unexpected keyword argument 'chrome_options'

the error appears.
If you look it up, you can see that the grammar has changed since 4.10.0 or later. Therefore, you must specify the old version of 4.9.0.

Although you have changed the contextual chromedriver directly in the current chromedriver directory, go to the https://chromedriver.chromium.org/home site designated by ChromeDriverManager to download the latest version (114.0.5735.90) within the site. So the current web driver version and the chromedriver version will be different. Since it will be posted on other websites from version 115 or higher, if you run the current code, it will continue to download and run the old version of the chromedriver.

As a result, it was found that the version comparison of chrome and chromedrivers in the host was not proceeding normally.
You can also see that the Download correct version at "http://chromedriver.chromium.org/downloads " and place in "./chromedriver statement is printed by continuously downloading and running the unwanted old version driver.
I also wonder if the chromedriver in the ./chromedriver directory is running.

There is a version mismatch problem, but crawling works.

**Comment by YoongiKim** [comment]
Thank's for help!
I updated the code and cleaned chromedriver files.
