### ISSUE TITLE
Chrome driver doesnt work

### ISSUE THREAD

**Issue by AIMads** [YoongiKim/AutoCrawler#59]
Options - skip:True, threads:4, google:True, naver:True, full_resolution:False, face:False, no_gui:False, limit:0, _proxy_list:['']
1 keywords found: ['wooden cat figurine']
[WDM] - 

[WDM] - ====== WebDriver manager ======
[WDM] - 

[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 117.0.5938
[WDM] - Current google-chrome version is 117.0.5938
[WDM] - Get LATEST driver version for 117.0.5938
[WDM] - Get LATEST driver version for 117.0.5938
Error occurred while initializing chromedriver - There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_117.0.5938
Error occurred while initializing chromedriver - There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_117.0.5938
Task ended. Pool join.
Data imbalance checking...
Data imbalance not detected.
End Program

**Comment by cloudlakecho** [comment]
Have you tried [this commit](https://github.com/YoongiKim/AutoCrawler/commit/e1311d78cee7b4ab986c03c331768dfccf4bf089). It looks like on September 4, 2023
