### ISSUE TITLE
Suggestion: Use Python Click for parsing command line arguments

### ISSUE THREAD

**Issue by suminb** [YoongiKim/AutoCrawler#6]
Although `argparser`, which is a part of the standard library, is a good solution, I'd recommend [Click](https://click.palletsprojects.com) for making command line tools. It comes with a full load of fancy features, but, most notably, it will just make your life way easier by eliminating a bunch of boilerplate code.

Take the following code for example (excerpted from `main.py`).

```python
    parser.add_argument('--face', type=str, default='false', help='Face search mode')
    # ...
    _face = False if str(args.face).lower() == 'false' else True
```

With Click, the code above can be replaced with:

```python
@click.option('--face', type=bool, default=True, help='Face search mode.')
```

**Comment by YoongiKim** [comment]
Thanks for nice tips!
I didn't like argparser's dirty code too. I'd use it after another projects.
But I had to minimize pip requirements, argparser seems better for auto crawler project.

Thank you!
