### ISSUE TITLE
How to Modify "div" and "img

### ISSUE THREAD

**Issue by cloudlakecho** [YoongiKim/AutoCrawler#60]

**Comment by YoongiKim** [comment]
Hello. I have fixed the issue. Please checkout.

**Comment by cloudlakecho** [comment]
@YoongiKim Thanks for updating the web page scraping code. 

Regarding the question, somehow I didn't put anything in this issue page. I guess some Github technical glitches. My issue page related to this is actually located at [How to Modify "div" and "img" Variable in "collect_links.py"](https://github.com/YoongiKim/AutoCrawler/issues/61#event-10651858473). Please, check details of my question at there.
