### ISSUE TITLE
How to Modify "div" and "img" Variable in "collect_links.py"

### ISSUE THREAD

**Issue by cloudlakecho** [YoongiKim/AutoCrawler#61]
How to modify "xpath" variable in "collect_links.py"? 

Here is details:

I ran this command: `python main.py --google=true --limit=10 --download_path=../../../Pictures/test --full=true`, but I am facing this error message:
```
[Exception occurred while collecting links from google_full] Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="n4hgof"]//img[@class="r48jcc pT0Scc iPVvYb"]"}
  (Session info: headless chrome=114.0.5735.198)
```

It looks like "div" and "img" variables need to be modified in "collect_links.py" ([code line](https://github.com/YoongiKim/AutoCrawler/blob/master/collect_links.py#L205))
```
xpath = '//div[@class="n4hgof"]//img[@class="r48jcc pT0Scc iPVvYb"]'
imgs = elem.find_elements(By.XPATH, xpath)
```

Instead of waiting the codebase update, I want to try by myself. I opened the source code of Google search result, but there are many "\<div class\>" variable in there webpage (HTML). At the same time, it is hard to find "\<img class\>" but I see "img scr" . 
  &emsp;&emsp; For example, I see these in "\<div class\>": "fR600b islir" or "mEQved GdCiyb aEY0r" before/near "\<img scr\>". 
How to find proper value for the variable from Google search result?

**Comment by YoongiKim** [comment]
You can check this.

[XPath selection]
https://www.w3schools.com/xml/xpath_syntax.asp

You can open chrome developer tools and select some buttons. And also test the xpath code using CTRL + F in the developer tool.

I will update the code soon, but it constantly changes, it's hard me to follow every updates.

**Comment by cloudlakecho** [comment]
@YoongiKim Thanks for the weblink. I will check. 

Yes, we understand that you couldn't chase every change in the Google side. You may consider putting comment(s) in the code section or related guide in ReadMe, so community could modify the code line by ourselves.
