### ISSUE TITLE
can not download

### ISSUE THREAD

**Issue by yangyuke001** [YoongiKim/AutoCrawler#7]
the error as blow:

Scraping links
Click time out - //div[@class="img_area _item"]
Click time out - //div[@class="img_area _item"]
Refreshing browser...
Scraping links
Click time out - //div[@data-ri="0"]
Refreshing browser...
Click time out - //div[@class="img_area _item"]
Refreshing browser...

pls help

**Comment by YoongiKim** [comment]
Hello.
Now problem fixed.
Thank you!
